name = "wptomodany"
main = "index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
account_id = "31da673118a0155294ac1ad73934ed4a"

[env.production]
vars = { ENVIRONMENT = "production" }

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
# MONDAY_API_TOKEN (secret)
# MONDAY_BOARD_ID (secret) 
# MONDAY_COLUMN_MAPPING (secret - JSON string)

# Custom domain routes (optional)
# [[env.production.routes]]
# pattern = "wptomonday.your-domain.com/*"
# zone_name = "your-domain.com"
